---
- name: create backend directory on EC2
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: copy files to backend
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: unzip backend directory
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: start application
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ~/src/migrations
    TYPEORM_MIGRATIONS: ~/src/migrations/*.ts
    TYPEORM_ENTITIES: ~/src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople.cvfalocpsmud.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: postgres
    TYPEORM_DATABASE: uda-pro3

- name: print environment variables
  become: true
  shell: |
    printenv
  register: printenv_out

- debug: var=printenv_out.stdout_lines
