---
- name: copy file to EC2
  become: yes
  template:
    src: files/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
- name: Unarchive backend files
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/
- name: start server
  become: true
  shell: |
    ls
    cd /home/ubuntu/backend
    ls
    pm2 start main.js -f